server:
  port: 1111
  hostname: eurekaServer1

eureka:
  instance:
    #eureka服务器的标识，如果是集群就可以写成 eurekaSer1,eurekaSer2,eurekaSer3..
    hostname: ${server.hostname}
  client:
    #registerWithEureka表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    registerWithEureka: false
    #fetchRegistry表示是否从eureka服务器获取注册信息，同上，这里不需要。
    fetchRegistry: false
    #开启客户端存活状态监测
    healthcheck:
      enabled: true
    serviceUrl:
      #defaultZone是设置eureka服务器所在的地址，查询服务和注册服务程序都注册到这个地址。
      defaultZone: http://localhost:1112/eureka/